# Your Config goes here
# Example:
# -----------------------------
#  BackupName:
#    backup_type: dir
#    source:
#      - /foo/bar/backup_dir
#    destination:
#      dropbox:
#        path: /foo/bar
#      local:
#        path: /foo/bar/destination_dir

