# Example
# -----------------------------
#  BackupName:
#    backup_type: dir
#    source:
#      - /foo/bar/backup_dir
#    destination:
#      dropbox:
#        path: /foo/bar
#      local:
#        path: /foo/bar/destination_dir


test:
  backup_type: dir
  source:
    - d:\Projects\test\test_source
  destination:
    dropbox:
      path: /test
    local:
      path: d:\Projects\test\test_backup
